"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { getAuthenticatedProfile, type SurProfile } from "@/app/lib/auth/session";
import { supabase } from "@/app/lib/supabase/client";

type Chat={id:string;status:string|null;updated_at:string|null};
type Message={id:string;sender_role:string|null;body:string|null;created_at:string|null};

export default function SupportPage(){
 const [profile,setProfile]=useState<SurProfile|null>(null),[chat,setChat]=useState<Chat|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState("");
 const endRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{void load()},[]);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function load(){setLoading(true);setError("");const current=await getAuthenticatedProfile();if(!current){setError("Please sign in again.");setLoading(false);return}setProfile(current);const {data:chats,error:chatError}=await supabase.from("support_chats").select("id,status,updated_at").eq("profile_id",current.id).order("updated_at",{ascending:false}).limit(1);if(chatError){setError("Support chat is temporarily unavailable.");setLoading(false);return}const active=(chats?.[0]||null) as Chat|null;setChat(active);if(active){const {data,error}=await supabase.from("support_messages").select("id,sender_role,body,created_at").eq("chat_id",active.id).order("created_at",{ascending:true});if(error)setError(error.message);else setMessages((data||[]) as Message[])}setLoading(false)}
 async function ensureChat(){if(chat)return chat;if(!profile)throw new Error("Please sign in again.");const {data,error}=await supabase.from("support_chats").insert({profile_id:profile.id,subject:"Support chat",status:"ADMIN_QUEUE",channel:"INVESTOR",escalated_at:new Date().toISOString()}).select("id,status,updated_at").single();if(error)throw error;const created=data as Chat;setChat(created);return created}
 async function send(){const clean=draft.trim();if(!clean||sending)return;setSending(true);setError("");try{const current=await ensureChat();const {data,error}=await supabase.from("support_messages").insert({chat_id:current.id,profile_id:profile?.id,sender_role:"CUSTOMER",body:clean}).select("id,sender_role,body,created_at").single();if(error)throw error;setMessages(rows=>[...rows,data as Message]);setDraft("");const {error:queueError}=await supabase.from("support_chats").update({status:"ADMIN_QUEUE",updated_at:new Date().toISOString()}).eq("id",current.id);if(queueError)setError("Message saved, but the Admin queue could not refresh. Do not resend; contact Support if no reply arrives.")}catch(value){setError(value instanceof Error?value.message:"Unable to send message.")}setSending(false)}
 return <main className="min-h-screen bg-[#f5f1e7] bg-cover bg-fixed bg-center px-3 py-4 text-[#102b23] sm:px-6 lg:py-8" style={{backgroundImage:"url('/sur-bg-app-light-v1.png')"}}><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-3xl flex-col overflow-hidden rounded-[2rem] border border-[#ded9cc] bg-white shadow-xl sm:min-h-[760px]">
  <header className="flex items-center justify-between gap-4 border-b border-[#e9e5da] bg-[#073d30] px-5 py-4 text-white sm:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#d9a93e] font-black text-[#163024]">AS</div><div><h1 className="font-black">Agarwood Support</h1><p className="text-xs font-bold text-emerald-100/70">We usually reply here after review.</p></div></div><Link href="/investor/my-trees" className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Close</Link></header>
  <section className="flex-1 overflow-y-auto bg-[#f7f5ee] p-4 sm:p-6">{loading?<p className="py-10 text-center text-sm font-bold text-[#718078]">Opening chat…</p>:messages.length===0?<div className="mx-auto mt-16 max-w-sm text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#e5f3eb] text-2xl">💬</div><h2 className="mt-4 text-xl font-black">How can we help?</h2><p className="mt-2 text-sm leading-6 text-[#6a7a74]">Send your message to the Agarwood Support Team.</p></div>:messages.map(message=>{const customer=String(message.sender_role).toUpperCase()==="CUSTOMER";return <div key={message.id} className={`mb-3 flex ${customer?"justify-end":"justify-start"}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 ${customer?"rounded-br-md bg-[#08745b] text-white":"rounded-bl-md border border-[#e2ded3] bg-white"}`}><p className="whitespace-pre-wrap text-sm font-medium leading-6">{message.body}</p><p className={`mt-1 text-[10px] font-bold ${customer?"text-white/55":"text-[#8a9691]"}`}>{time(message.created_at)}</p></div></div>})}<div ref={endRef}/></section>
  {error&&<div className="border-t border-red-100 bg-red-50 px-5 py-3 text-sm font-bold text-red-700">{error}</div>}
  <footer className="border-t border-[#e9e5da] bg-white p-3 sm:p-4"><div className="flex items-end gap-2"><textarea value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send()}}} rows={1} placeholder="Type your message…" className="max-h-32 min-h-12 flex-1 resize-none rounded-2xl border border-[#ded9cc] bg-[#faf9f5] px-4 py-3 text-sm font-bold outline-none focus:border-[#08745b]"/><button onClick={()=>void send()} disabled={sending||!draft.trim()} aria-label="Send message" className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#d9a93e] text-xl font-black text-[#183126] disabled:opacity-40">➤</button></div></footer>
 </div></main>
}
function time(value:string|null){if(!value)return "";return new Date(value).toLocaleString("en-PH",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}
