"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/app/lib/supabase/client";
type Payment={id:string;tree_id:string;sender_name:string;payment_reference:string;payment_date:string;receipt_path:string;plan:string;months:number;exact_total:number;status:string;review_note:string|null};
export default function AdminCarePayments(){
 const [rows,setRows]=useState<Payment[]>([]),[selected,setSelected]=useState<Payment|null>(null),[note,setNote]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<{id:string;url:string}|null>(null);
 async function load(){const result=await supabase.from("sur_care_payments").select("id,tree_id,sender_name,payment_reference,payment_date,receipt_path,plan,months,exact_total,status,review_note").order("created_at",{ascending:false}).limit(200);if(result.error)throw new Error("Care payment queue unavailable. Check migration 103 before processing.");setRows(result.data||[]);setSelected(old=>(result.data||[]).find(p=>p.id===old?.id)||null)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 async function openReceipt(){if(!selected||busy)return;const id=selected.id;setBusy(true);setMessage("");try{const result=await supabase.storage.from("sur-payment-proofs").createSignedUrl(selected.receipt_path,120);if(result.error)throw new Error(result.error.message);setReceipt({id,url:result.data.signedUrl})}catch(e){setMessage(e instanceof Error?e.message:"Receipt unavailable")}finally{setBusy(false)}}
 async function review(decision:string){if(!selected||busy)return;if(note.trim().length<3){setMessage("Add a verification or rejection note first.");return}setBusy(true);setMessage("");try{const result=await supabase.rpc("sur_admin_review_care_payment",{p_payment:selected.id,p_decision:decision,p_note:note.trim()});if(result.error)throw new Error(result.error.message);await load();setNote("");setMessage(`${decision}: payment recorded. No bank transfer was performed.`)}catch(e){setMessage((e instanceof Error?e.message:"Connection interrupted.")+" Refresh history before retrying.")}finally{setBusy(false)}}
 return <section className="mt-5 rounded-3xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">Care payments</h2><button disabled={busy} onClick={()=>void load().catch(e=>setMessage(e.message))} className="rounded-xl border px-4 py-3">Refresh care payments</button></div><p className="mt-2 text-sm text-slate-600">Verify the external Maya transaction before approving. Approval adds care coverage, not wallet balance.</p>{message&&<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{message}</p>}<div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="space-y-2">{!rows.length&&<p>No care payment records loaded.</p>}{rows.map(p=><button key={p.id} disabled={busy} onClick={()=>{setSelected(p);setNote("");setReceipt(null)}} className={`w-full rounded-xl border p-4 text-left ${selected?.id===p.id?"border-emerald-600 bg-emerald-50":""}`}><b>{p.sender_name} · ₱{Number(p.exact_total).toLocaleString("en-PH")}</b><p className="mt-1 text-sm">{p.plan==="MONTHLY"?`${p.months} months`:"One-time care"} · {p.status}</p></button>)}</div>{selected&&<div className="min-w-0 rounded-2xl border p-4"><h3 className="font-bold">Payment review</h3><p className="mt-3 break-all text-sm">Tree record: {selected.tree_id}</p><p className="mt-2 break-all text-sm">Maya reference: {selected.payment_reference}</p><p className="mt-2 text-sm">Payment date: {selected.payment_date}</p><button disabled={busy} onClick={()=>void openReceipt()} className="mt-4 rounded-xl border p-3">Prepare private receipt</button>{receipt?.id===selected.id&&<a target="_blank" rel="noreferrer" href={receipt.url} className="ml-3 underline">Open (2 minutes)</a>}{selected.status==="PENDING"?<><label className="mt-4 block text-sm font-bold">Review note<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy} className="mt-2 w-full rounded-xl border p-3"/></label><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void review("APPROVED")} className="rounded-xl bg-emerald-900 px-5 py-3 font-bold text-white">Approve coverage</button><button disabled={busy} onClick={()=>void review("REJECTED")} className="rounded-xl border border-red-300 px-5 py-3 font-bold text-red-800">Reject payment</button></div></>:<p className="mt-4">{selected.status}: {selected.review_note}</p>}</div>}</div></section>;
}
