"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect,useState } from "react";
import { getAuthenticatedProfile,type SurProfile } from "@/app/lib/auth/session";
import { supabase } from "@/app/lib/supabase/client";

type Row=Record<string,unknown>;
const nav=[["Home","/investor/dashboard","⌂"],["My Trees","/investor/my-trees","🌳"],["Wallet","/investor/wallet","₱"],["Support","/investor/support","?"],["Account","/investor/profile","●"]] as const;

export default function SimpleCustomerDashboard(){
 const [profile,setProfile]=useState<SurProfile|null>(null),[trees,setTrees]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[notices,setNotices]=useState<Row[]>([]),[wallet,setWallet]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){
  setLoading(true);setError("");const current=await getAuthenticatedProfile();if(!current){setError("Please sign in again.");setLoading(false);return}setProfile(current);
  const [treeResult,orderResult,walletResult,noticeResult]=await Promise.all([
   supabase.from("sur_trees").select("id,tree_id,species,status,planted_at,created_at").eq("profile_id",current.id).order("created_at",{ascending:false}).limit(20),
   supabase.from("sur_tree_orders").select("id,order_no,status,exact_total,created_at").eq("profile_id",current.id).order("created_at",{ascending:false}).limit(10),
   supabase.from("wallets").select("balance,updated_at").eq("profile_id",current.id).maybeSingle(),
   supabase.from("notifications").select("id,title,message,is_read,created_at").eq("profile_id",current.id).order("created_at",{ascending:false}).limit(10),
  ]);
  if(treeResult.error) setError("Some account information could not load. Your records remain safe.");setTrees((treeResult.data||[]) as Row[]);setOrders((orderResult.data||[]) as Row[]);setWallet((walletResult.data||null) as Row|null);setNotices((noticeResult.data||[]) as Row[]);setLoading(false);
 }
 const name=String(profile?.full_name||"Co-Planter").split(" ")[0],status=String(profile?.account_status||"PENDING").toUpperCase(),pending=["PENDING","UNDER_REVIEW"].includes(status),pendingOrders=orders.filter(x=>["PENDING_VERIFICATION","MANUAL_REVIEW","PENDING"].includes(String(x.status).toUpperCase())),unread=notices.filter(x=>!x.is_read).length,tree=trees[0],order=pendingOrders[0];
 const next= pending?{title:"Account review in progress",body:"You may browse tree packages while Agarwood Support reviews your account.",href:"/investor/marketplace",action:"Browse trees"}:order?{title:"Payment is being reviewed",body:`Order ${String(order.order_no||"")} will become active only after Admin approval.`,href:"/investor/marketplace",action:"View order"}:trees.length?{title:"Your tree is being cared for",body:"No action is required today. Check the latest approved care record.",href:"/investor/my-trees",action:"Open My Trees"}:{title:"Choose your first agarwood tree",body:"Buy a tree package and submit the exact payment for Admin review.",href:"/investor/marketplace",action:"Browse trees"};
 return <main className="min-h-screen bg-[#f7f3e8] pb-24 text-[#12231c] md:pb-10">
  <header className="sticky top-0 z-30 border-b border-[#0b3d2e]/10 bg-[#f7f3e8]/95 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-6xl items-center justify-between px-4 md:min-h-20 md:px-6"><Link href="/" className="flex items-center gap-3"><Image src="/sur-logo.png" alt="SUR Aloeswood" width={44} height={44} className="rounded-full border-2 border-[#dbc27e]"/><span><b className="block text-xs tracking-[.15em] md:text-sm">SUR ALOESWOOD</b><small className="hidden text-[10px] font-bold tracking-[.12em] text-[#64756d] sm:block">MY TREE APP</small></span></Link><nav className="hidden gap-1 md:flex">{nav.map(([label,href])=><Link key={href} href={href} className={`rounded-full px-4 py-3 text-sm font-extrabold ${label==="Home"?"bg-[#0b3d2e] text-white":"text-[#0b3d2e] hover:bg-[#e7f5ed]"}`}>{label}</Link>)}</nav></div></header>
  <div className="mx-auto max-w-6xl px-4 py-6 md:px-6 md:py-10">
   <section className="overflow-hidden rounded-[1.75rem] bg-[#0b3d2e] text-white shadow-[0_24px_70px_rgba(15,48,36,.16)] md:grid md:grid-cols-[1.15fr_.85fr]"><div className="p-6 md:p-10"><p className="text-[11px] font-black tracking-[.22em] text-[#b5d5c6]">YOUR TREE HOME</p><h1 className="mt-3 text-4xl font-black tracking-tight md:text-6xl">Hello, {name}.</h1><p className="mt-4 max-w-lg text-sm leading-7 text-white/70">Everything important about your trees, payments, care, and documents—without the technical clutter.</p><span className="mt-6 inline-flex rounded-full bg-white/10 px-4 py-2 text-xs font-black">ACCOUNT: {pretty(status)}</span></div><div className="relative min-h-56 md:min-h-full"><Image src="/sur-hero-tree-v1.png" alt="Agarwood plantation" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#0b3d2e] via-transparent to-transparent"/></div></section>
   {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div>}
   <section className="mt-5 rounded-[1.5rem] border border-[#d5a344]/35 bg-[#fff8dc] p-5 md:flex md:items-center md:justify-between md:gap-5"><div><p className="text-[10px] font-black tracking-[.18em] text-[#8a6820]">YOUR NEXT STEP</p><h2 className="mt-2 text-xl font-black md:text-2xl">{loading?"Loading your account…":next.title}</h2><p className="mt-2 text-sm leading-6 text-[#68501b]">{loading?"Please wait while we check your records.":next.body}</p></div>{!loading&&<Link href={next.href} className="mt-4 block rounded-2xl bg-[#0b3d2e] px-5 py-4 text-center text-sm font-black text-white md:mt-0">{next.action}</Link>}</section>
   <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="MY TREES" value={loading?"—":String(trees.length)} detail="Official Tree IDs" href="/investor/my-trees"/><Metric label="WALLET BALANCE" value={loading?"—":peso(Number(wallet?.balance||0))} detail="See balance history" href="/investor/wallet"/><Metric label="ORDERS IN REVIEW" value={loading?"—":String(pendingOrders.length)} detail="Waiting for Admin" href="/investor/marketplace"/><Metric label="UNREAD MESSAGES" value={loading?"—":String(unread)} detail="Updates and notices" href="/investor/notifications"/></section>
   <section className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-[1.75rem] border border-[#0b3d2e]/10 bg-white p-5 shadow-sm md:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#167553]">TREE AT A GLANCE</p><h2 className="mt-2 text-2xl font-black">{tree?String(tree.tree_id):"No approved tree yet"}</h2></div><Link href="/investor/my-trees" className="text-xs font-black text-[#167553]">View all</Link></div>{tree?<div className="mt-5 grid gap-4 sm:grid-cols-[150px_1fr]"><div className="relative min-h-40 overflow-hidden rounded-2xl"><Image src="/sur-hero-tree-v1.png" alt="Agarwood tree" fill className="object-cover"/></div><div className="grid grid-cols-2 gap-3"><Info label="SPECIES" value={String(tree.species||"Agarwood")}/><Info label="STATUS" value={pretty(String(tree.status||"Pending"))}/><Info label="PURCHASED" value={date(String(tree.created_at||""))}/><Info label="PLANTED" value={date(String(tree.planted_at||""))}/></div></div>:<div className="mt-5 rounded-2xl bg-[#f8faf8] p-6 text-sm leading-6 text-[#64756d]">After payment approval, your Tree ID and contract will appear here automatically.</div>}</div>
    <div className="rounded-[1.75rem] border border-[#0b3d2e]/10 bg-white p-5 shadow-sm md:p-7"><p className="text-[10px] font-black tracking-[.18em] text-[#167553]">QUICK ACTIONS</p><div className="mt-4 grid gap-3"><Action href="/investor/marketplace" title="Buy a tree" detail="Choose a package"/><Action href="/investor/care-services" title="Care & updates" detail="View approved reports"/><Action href="/legalities" title="Documents" detail="Contracts and certificates"/><Action href="/investor/support" title="Ask Support" detail="Talk to Agarwood Support"/></div></div></section>
  </div><nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-[#dbe5df] bg-white/95 px-2 pb-[calc(.5rem+env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl md:hidden">{nav.map(([label,href,icon])=><Link key={href} href={href} className={`rounded-xl py-2 text-center text-[10px] font-extrabold ${label==="Home"?"bg-[#e7f5ed] text-[#0b3d2e]":"text-[#718078]"}`}><span className="mb-1 block text-lg">{icon}</span>{label}</Link>)}</nav>
 </main>
}
function Metric({label,value,detail,href}:{label:string;value:string;detail:string;href:string}){return <Link href={href} className="rounded-2xl border border-[#0b3d2e]/10 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md md:p-5"><span className="text-[9px] font-black tracking-[.12em] text-[#64756d]">{label}</span><b className="mt-2 block text-2xl md:text-3xl">{value}</b><small className="mt-2 block font-bold text-[#167553]">{detail} →</small></Link>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#f8f7f0] p-4"><span className="text-[9px] font-black tracking-[.1em] text-[#64756d]">{label}</span><b className="mt-2 block text-sm">{value}</b></div>}
function Action({href,title,detail}:{href:string;title:string;detail:string}){return <Link href={href} className="flex items-center justify-between rounded-2xl border border-[#dbe5df] p-4 hover:bg-[#e7f5ed]"><span><b className="block text-sm">{title}</b><small className="mt-1 block text-[#64756d]">{detail}</small></span><b>›</b></Link>}
function pretty(v:string){return v.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase())}function peso(v:number){return new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:2}).format(v)}function date(v:string){if(!v)return "Pending";return new Intl.DateTimeFormat("en-PH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v))}
