"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, type PointerEvent, type ReactNode } from "react";
import { getAuthenticatedProfile, type SurProfile } from "@/app/lib/auth/session";
import { supabase } from "@/app/lib/supabase/client";
import TreeIdentityQr from "@/app/components/TreeIdentityQr";
import LogoutButton from "@/app/components/LogoutButton";
import CareCoverageNotice from "@/app/components/CareCoverageNotice";
import BuyTreeModal from "@/app/components/BuyTreeModal";

type Row=Record<string,unknown>;
type Tree={id:string;tree_id:string;nickname?:string|null;species:string;care_plan:string;status:string;planted_at:string|null;activated_at:string|null;created_at:string;contract:{id:string;status:string}|null};
const topNav=[["Wallet","/investor/wallet","wallet"],["Support","/investor/support","support"],["Account","/investor/profile","account"]] as const;

export default function SimpleMyTrees(){
 const [profile,setProfile]=useState<SurProfile|null>(null),[trees,setTrees]=useState<Tree[]>([]),[updates,setUpdates]=useState<Row[]>([]),[index,setIndex]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[buyOpen,setBuyOpen]=useState(false);
 const [editingName,setEditingName]=useState(false),[nameDraft,setNameDraft]=useState(""),[savingName,setSavingName]=useState(false),[nameMessage,setNameMessage]=useState("");
 const swipeStart=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{void load()},[]);
 async function load(){
  setLoading(true);setError("");const current=await getAuthenticatedProfile();
  if(!current){setError("We could not verify your account. Please sign in again.");setLoading(false);return} setProfile(current);
  const treeResult=await supabase.from("sur_trees").select("id,tree_id,species,care_plan,status,planted_at,activated_at,created_at,sur_contracts(id,status)").eq("profile_id",current.id).order("created_at",{ascending:false});
  if(treeResult.error){setError("Your tree records are temporarily unavailable. Please try again or contact support.");setLoading(false);return}
  let ownTrees=(treeResult.data||[]).map(raw=>{const linked=Array.isArray(raw.sur_contracts)?raw.sur_contracts[0]:raw.sur_contracts;return {...raw,contract:linked||null} as Tree});
  if(ownTrees.length){const nicknameResult=await supabase.from("sur_trees").select("id,nickname").in("id",ownTrees.map(item=>item.id));if(!nicknameResult.error){const names=new Map((nicknameResult.data||[]).map(item=>[item.id,item.nickname]));ownTrees=ownTrees.map(item=>({...item,nickname:names.get(item.id)||null}))}}
  setTrees(ownTrees);setIndex(0);
  const ownIds=ownTrees.map(tree=>tree.id);if(!ownIds.length){setUpdates([]);setLoading(false);return}
  const updateResult=await supabase.from("sur_tree_updates").select("id,tree_id,observed_on,health_status,notes,photo_path,created_at").in("tree_id",ownIds).eq("status","APPROVED").order("observed_on",{ascending:false}).limit(100);
  if(updateResult.error){setError("Care updates could not load. Please retry.");setUpdates([]);setLoading(false);return}
  const signed=await Promise.all(((updateResult.data||[]) as Row[]).map(async row=>{const path=String(row.photo_path||"");if(!path)return row;const {data}=await supabase.storage.from("sur-tree-evidence").createSignedUrl(path,600);return {...row,photo_url:data?.signedUrl||""}}));setUpdates(signed);setLoading(false);
 }
 function previousTree(){setIndex(current=>(current-1+trees.length)%trees.length)}
 function nextTree(){setIndex(current=>(current+1)%trees.length)}
 function startRename(){if(!tree)return;setNameDraft(tree.nickname||treeName);setNameMessage("");setEditingName(true)}
 async function saveTreeName(){if(!tree)return;const clean=nameDraft.trim().replace(/\s+/g," ");if(clean.length<2||clean.length>40){setNameMessage("Use 2 to 40 characters.");return}setSavingName(true);setNameMessage("");const {error:renameError}=await supabase.rpc("sur_rename_own_tree",{p_tree_id:tree.id,p_nickname:clean});setSavingName(false);if(renameError){setNameMessage("Could not save the name. Please retry or contact Support.");return}setTrees(current=>current.map(item=>item.id===tree.id?{...item,nickname:clean}:item));setEditingName(false)}
 function beginSwipe(event:PointerEvent<HTMLElement>){if(trees.length>1&&event.pointerType!=="mouse")swipeStart.current={x:event.clientX,y:event.clientY}}
 function endSwipe(event:PointerEvent<HTMLElement>){const start=swipeStart.current;swipeStart.current=null;if(!start||trees.length<2)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.abs(dx)<60||Math.abs(dx)<=Math.abs(dy)*1.2)return;if(dx<0)nextTree();else previousTree()}
 const tree=trees[index]||null,latest=updates.find(row=>String(row.tree_id)===tree?.id)||null,pending=profile&&["PENDING","UNDER_REVIEW"].includes(String(profile.account_status).toUpperCase()),needsSign=tree?.contract?.status==="CUSTOMER_SIGNATURE_PENDING",photo=String(latest?.photo_url||"/sur-hero-tree-v1.png");
 const firstName=String(profile?.full_name||"Co-Planter").trim().split(/\s+/)[0];
 const fallbackTreeName=`${firstName}'s Agarwood Tree${trees.length>1?` ${index+1}`:""}`,treeName=tree?.nickname||fallbackTreeName,recordNo=tree?.tree_id?.split("-").at(-1)||"Pending";
 const growthStart=tree?.planted_at||null,growth=growthProgress(growthStart),customerStatus=({HEALTHY:"Healthy",NEEDS_ATTENTION:"Needs attention",TREATMENT:"Under treatment",DAMAGED:"Damaged",REPLACEMENT_REVIEW:"Replacement review"} as Record<string,string>)[String(latest?.health_status||"").toUpperCase()]||"Awaiting update";
 return <main className="min-h-screen bg-[#f7f3e8] bg-cover bg-fixed bg-center pb-10 text-[#12231c]" style={{backgroundImage:"url('/sur-bg-app-light-v1.png')"}}>
  <header className="sticky top-0 z-30 border-b border-[#0b3d2e]/10 bg-[#f7f3e8]/95 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1380px] items-center justify-between gap-3 px-4 md:min-h-20 md:px-6"><Link href="/investor/my-trees" className="flex min-w-0 items-center gap-3"><Image src="/sur-logo.png" alt="SUR Aloeswood" width={44} height={44} className="rounded-full border-2 border-[#dbc27e]"/><span><b className="block truncate text-xs tracking-[.15em] md:text-sm">SUR ALOESWOOD</b><small className="hidden text-[10px] font-bold tracking-[.12em] text-[#64756d] sm:block">MY TREE APP</small></span></Link><nav className="hidden items-center gap-1 lg:flex">{topNav.map(([label,href,icon])=><Link key={href} href={href} className="flex min-h-11 items-center gap-2 rounded-full px-4 py-3 text-sm font-extrabold text-[#0b3d2e] transition hover:bg-[#e7f5ed]"><NavIcon name={icon}/>{label}</Link>)}<LogoutButton icon={<NavIcon name="logout"/>} className="ml-1 flex min-h-11 items-center gap-2 rounded-full border border-red-200 bg-red-50 px-4 py-3 text-sm font-black text-red-800 transition hover:bg-red-100 disabled:opacity-60"/></nav><details className="relative lg:hidden"><summary className="grid h-11 w-11 cursor-pointer list-none place-items-center rounded-full border border-[#dbe5df] bg-white text-xl font-black text-[#0b3d2e]">☰</summary><div className="absolute right-0 mt-2 w-56 overflow-hidden rounded-2xl border border-[#dbe5df] bg-white p-2 shadow-2xl">{topNav.map(([label,href,icon])=><Link key={href} href={href} className="flex min-h-12 items-center gap-3 rounded-xl px-4 py-3 text-sm font-extrabold text-[#0b3d2e] hover:bg-[#e7f5ed]"><NavIcon name={icon}/>{label}</Link>)}<LogoutButton icon={<NavIcon name="logout"/>} className="mt-1 flex min-h-12 w-full items-center gap-3 rounded-xl bg-red-50 px-4 py-3 text-left text-sm font-black text-red-800 hover:bg-red-100 disabled:opacity-60"/></div></details></div></header>
  <div className="mx-auto max-w-[1380px] px-3 py-4 sm:px-4 md:px-6 md:py-7"><section className="overflow-hidden rounded-[1.5rem] bg-[#073c2d] p-5 text-white shadow-[0_18px_50px_rgba(7,60,45,.18)] sm:rounded-[1.75rem] md:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#b9d9ca] sm:text-xs">Welcome back</p><h1 className="mt-1 break-words text-2xl font-black md:text-3xl">Hello, {firstName}</h1><p className="mt-2 text-sm text-white/70">Your trees, records, and next actions are ready here.</p></div>{!loading&&trees.length>0&&<button onClick={()=>setBuyOpen(true)} className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-2xl bg-[#d5a344] px-6 py-3 text-sm font-black text-[#2e2108] shadow-sm">＋ Buy Tree</button>}</div></section>
   {pending&&<Notice><b>Account pending approval.</b> You may browse tree packages while Agarwood Support reviews your account.</Notice>}{error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div>}
   {loading?<Panel>Loading your tree records…</Panel>:!tree?<Empty onBuy={()=>setBuyOpen(true)}/>:<div className="relative mt-6"><div className="mb-4 flex items-center justify-between gap-3 rounded-2xl border border-white/60 bg-[#f7f3e8]/90 px-4 py-3 shadow-sm backdrop-blur-md sm:px-5"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#167553] sm:text-xs">Your collection</p><h2 className="mt-0.5 text-xl font-black sm:text-2xl">My Trees</h2></div><div className="flex shrink-0 items-center gap-1.5 sm:gap-2"><Arrow label="Previous tree" disabled={trees.length<2} onClick={previousTree}>‹</Arrow><b className="hidden min-w-20 text-center text-xs text-[#50645c] min-[390px]:block">Tree {index+1} of {trees.length}</b><Arrow label="Next tree" disabled={trees.length<2} onClick={nextTree}>›</Arrow></div></div>
    <article key={tree.id} onPointerDown={beginSwipe} onPointerUp={endSwipe} onPointerCancel={()=>{swipeStart.current=null}} className="touch-pan-y animate-[tree-in_.22s_ease-out] overflow-hidden rounded-[1.5rem] border border-[#0b3d2e]/10 bg-white shadow-[0_24px_70px_rgba(15,48,36,.14)] sm:rounded-[1.75rem] md:grid md:min-h-[520px] md:grid-cols-[40%_60%] xl:grid-cols-[43%_57%]"><div className="relative min-h-[clamp(19rem,82vw,27rem)] bg-[#dcebdc] md:min-h-full"><Image src={photo} alt={`Care record for ${tree.tree_id}`} fill priority sizes="(max-width: 767px) 100vw, (max-width: 1279px) 40vw, 43vw" unoptimized={photo.startsWith("http")} className="pointer-events-none select-none object-cover object-[62%_center] md:object-center"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#06251c]/65 to-transparent"/><b className="absolute bottom-4 left-4 max-w-[calc(100%-2rem)] truncate rounded-xl bg-white/95 px-3 py-2 text-xs text-[#0b3d2e] shadow-sm sm:bottom-5 sm:left-5 sm:rounded-2xl sm:px-4 sm:py-3 sm:text-sm">Record No. {recordNo}</b></div>
     <div className="min-w-0 p-5 sm:p-6 lg:p-8"><div className="flex items-start justify-between gap-3 sm:gap-4"><div className="min-w-0 flex-1">{editingName?<div><label className="text-[10px] font-black uppercase tracking-[.12em] text-[#167553]">Tree nickname</label><input autoFocus value={nameDraft} maxLength={40} onChange={event=>setNameDraft(event.target.value)} className="mt-2 w-full rounded-2xl border border-[#bfe3d0] bg-[#f8faf8] px-4 py-3 font-serif text-xl font-black text-[#0b3d2e] outline-none focus:ring-2 focus:ring-[#167553]/20"/><div className="mt-2 flex flex-wrap items-center gap-2"><button onClick={()=>void saveTreeName()} disabled={savingName} className="rounded-xl bg-[#0b3d2e] px-4 py-2 text-xs font-black text-white disabled:opacity-50">{savingName?"Saving…":"Save name"}</button><button onClick={()=>{setEditingName(false);setNameMessage("")}} className="rounded-xl border border-[#dbe5df] px-4 py-2 text-xs font-black text-[#64756d]">Cancel</button></div>{nameMessage&&<p className="mt-2 text-xs font-bold text-red-700">{nameMessage}</p>}</div>:<h3 className="break-words font-serif text-[clamp(1.75rem,3vw,2.75rem)] font-black leading-[1.02] tracking-[-.025em] text-[#0b3d2e]">{treeName}</h3>}<p className="mt-3 text-xs font-bold leading-5 text-[#64756d] sm:text-sm">Owned since {date(tree.created_at)} · {pretty(tree.care_plan)} Care</p><p className="mt-1 text-[10px] font-black uppercase tracking-[.12em] text-[#8a9891]">Official record {recordNo}</p></div><div className="flex shrink-0 flex-col items-center gap-2"><TreeIdentityQr code={tree.tree_id}/><button onClick={startRename} aria-label="Rename this tree" className="rounded-full border border-[#dbe5df] bg-white px-3 py-2 text-[10px] font-black text-[#167553] transition hover:bg-[#e7f5ed]">✎ Rename</button></div></div>
      <CareCoverageNotice key={tree.id} treeId={tree.id}/>
      <div className="mt-6 grid grid-cols-3 gap-1.5 sm:gap-2 xl:mt-7"><Stat label="STATUS" value={customerStatus}/><Stat label="TREE AGE" value={treeAge(growthStart)}/><ProgressStat value={growth}/></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-3"><Action href="/investor/care-services" label="Care Journal" primary/><LegalAction treeId={tree.id} pending={needsSign}/><Action href="/investor/referrals" label="Referral & Share"/></div>
      <section className="mt-7 border-t border-[#dbe5df] pt-6"><div className="flex justify-between gap-3"><h3 className="text-xl font-black">Latest approved update</h3><Link href="/investor/care-services" className="text-xs font-black text-[#167553]">View history</Link></div>{latest?<div className="mt-4 grid grid-cols-[64px_1fr] gap-3 rounded-2xl bg-[#f8faf8] p-3"><div className="relative h-16 overflow-hidden rounded-xl"><Image src={photo} alt="Latest care update" fill unoptimized={photo.startsWith("http")} className="object-cover"/></div><div><b className="text-sm">Care update · {date(String(latest.observed_on||latest.created_at))}</b><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#64756d]">{String(latest.notes||"Reviewed and approved by Admin.")}</p></div></div>:<p className="mt-4 rounded-2xl bg-[#f8faf8] p-4 text-sm text-[#64756d]">No approved update yet. It will appear after Admin reviews the caretaker submission.</p>}</section>
     </div></article>{trees.length>1&&<div className="mt-4 flex items-center justify-center gap-2 lg:hidden" aria-label={`Tree ${index+1} of ${trees.length}`}>{trees.map((item,itemIndex)=><button key={item.id} onClick={()=>setIndex(itemIndex)} aria-label={`Show tree ${itemIndex+1}`} className={`h-2.5 rounded-full transition-all ${itemIndex===index?"w-7 bg-[#0b3d2e]":"w-2.5 bg-[#b8c5bd]"}`}/>)}</div>}</div>}
  </div><BuyTreeModal open={buyOpen} onClose={()=>setBuyOpen(false)} onSubmitted={()=>void load()}/>
 </main>
}
function Notice({children}:{children:ReactNode}){return <div className="mt-6 flex gap-3 rounded-2xl border border-[#efd489] bg-[#fff8dc] p-4 text-sm text-[#68501b]"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-[#d5a344] ring-4 ring-[#f8e7b7]"/><p>{children}</p></div>}
function Panel({children}:{children:ReactNode}){return <div className="mt-8 rounded-3xl bg-white p-10 text-center font-bold text-[#64756d]">{children}</div>}
function Empty({onBuy}:{onBuy:()=>void}){return <section className="mt-8 rounded-[2rem] bg-white p-8 text-center shadow-xl"><Image src="/app-assets/empty-my-trees-v1.png" alt="Agarwood tree" width={340} height={260} className="mx-auto h-48 w-auto object-contain"/><h2 className="mt-5 text-2xl font-black">Your first tree will appear here</h2><p className="mx-auto mt-3 max-w-md text-sm text-[#64756d]">After payment approval, your Tree ID, contract, QR record, and care updates will be organized here.</p><button onClick={onBuy} className="mt-6 inline-flex rounded-2xl bg-[#0b3d2e] px-6 py-4 text-sm font-black text-white">Buy Tree</button></section>}
function Arrow({label,disabled,onClick,children}:{label:string;disabled:boolean;onClick:()=>void;children:ReactNode}){return <button aria-label={label} disabled={disabled} onClick={onClick} className="pointer-events-auto grid h-10 w-10 place-items-center rounded-full border border-[#dbe5df] bg-white text-2xl font-light text-[#0b3d2e] shadow-md transition hover:scale-105 hover:bg-[#e7f5ed] disabled:opacity-40 sm:h-12 sm:w-12 sm:text-3xl">{children}</button>}
function Stat({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl border border-[#efede2] bg-[#f8f7f0] p-2.5 sm:rounded-2xl sm:p-4"><span className="block truncate text-[8px] font-black tracking-[.08em] text-[#64756d] sm:text-[10px] sm:tracking-[.1em]">{label}</span><b className="mt-2 block break-words text-xs leading-4 sm:text-sm sm:leading-5">{value}</b></div>}
function ProgressStat({value}:{value:number}){return <div className="min-w-0 rounded-xl border border-[#d8eadf] bg-[#f2f8f4] p-2.5 sm:rounded-2xl sm:p-4"><span className="block truncate text-[8px] font-black tracking-[.05em] text-[#64756d] sm:text-[10px] sm:tracking-[.08em]">GROWTH</span><b className="mt-2 block text-xs text-[#167553] sm:text-sm">{value.toFixed(1)}%</b><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#dce8e0] sm:h-2.5"><div className="h-full rounded-full bg-gradient-to-r from-[#167553] to-[#d5a344] transition-[width] duration-500" style={{width:`${value}%`}}/></div><p className="mt-1 hidden text-[9px] font-bold text-[#718078] sm:block">4.5-year estimate</p></div>}
function Action({href,label,primary=false}:{href:string;label:string;primary?:boolean}){return <Link href={href} className={`rounded-2xl border p-4 text-center text-sm font-black text-[#0b3d2e] ${primary?"border-[#bfe3d0] bg-[#e7f5ed]":"border-[#dbe5df]"}`}>{label}</Link>}
function LegalAction({pending,treeId}:{pending:boolean;treeId:string}){return <Link href={`/legalities?tree=${treeId}`} className="relative rounded-2xl border border-[#dbe5df] p-4 text-center text-sm font-black text-[#0b3d2e] transition hover:bg-[#f8faf8]">Legals{pending&&<span className="absolute -right-2 -top-2 grid h-6 min-w-6 place-items-center rounded-full bg-red-600 px-1 text-[11px] font-black text-white shadow-md" aria-label="1 legal action required">1</span>}</Link>}
function NavIcon({name}:{name:string}){const common={width:18,height:18,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(name==="wallet")return <svg {...common}><path d="M4 7.5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a3 3 0 0 1-3-3v-10a3 3 0 0 1 3-3h12"/><path d="M16 12h4v4h-4a2 2 0 0 1 0-4Z"/></svg>;if(name==="support")return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="M8.5 9a3.5 3.5 0 1 1 5.4 2.94c-1.1.7-1.9 1.2-1.9 2.56"/><path d="M12 18h.01"/></svg>;if(name==="account")return <svg {...common}><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>;if(name==="settings")return <svg {...common}><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.12.37.35.7.66.94.3.24.68.37 1.07.37H21v4h-.1A1.7 1.7 0 0 0 19.4 15Z"/></svg>;return <svg {...common}><path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></svg>}
function pretty(v:string){return v.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase())} function date(v?:string|null){return v?new Intl.DateTimeFormat("en-PH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v)):"Date pending"} function elapsedDays(v?:string|null){if(!v||!Number.isFinite(new Date(v).getTime()))return 0;return Math.max(1,Math.floor((Date.now()-new Date(v).getTime())/86400000)+1)} function treeAge(v?:string|null){const days=elapsedDays(v);if(!days)return "Planting pending";if(days<365)return `Day ${days}`;const years=Math.floor(days/365),remaining=days%365;return `${years} year${years===1?"":"s"}${remaining?`, ${remaining} day${remaining===1?"":"s"}`:""}`} function growthProgress(v?:string|null){const totalDays=Math.round(365.25*4.5);return Math.min(100,Math.max(0,(elapsedDays(v)/totalDays)*100))}
