import Link from "next/link";

const daily=[
 ["Verify payments","Open Tree Orders. Compare sender, reference, date, amount and receipt with the official Maya transaction before approval.","/admin/orders"],
 ["Review farm evidence","Open Tree Maintenance. Approve only clear proof linked to the correct Tree ID; return incomplete evidence with a reason.","/admin/tree-maintenance"],
 ["Process support","Reply as Agarwood Support Team. Resolve with a final note; only admin closes tickets.","/admin/support"],
 ["Review withdrawals","Confirm KYC, legal name, wallet hold, fee and destination. Upload payout proof before marking paid.","/admin/treasury"],
];
const emergency=[
 ["Duplicate or wrong money entry","Do not delete the original. Post a documented correction/reversal through the approved ledger flow."],
 ["Wrong tree owner","Stop processing. Use Guardian preview and an ownership correction with reason, evidence and permanent audit."],
 ["Database/setup error","Do not paste random SQL. Check Guardian and the migration verification output; restore from the last tested backup if data was damaged."],
 ["Admin account inaccessible","Use the registered-email password-reset process. Never create an unlinked profile or edit auth identifiers by guess."],
];
export default function OperationsPage(){return <main className="min-h-screen bg-[#f4f7f2] p-5 text-slate-950 lg:p-8"><div className="mx-auto max-w-7xl"><header className="rounded-[2rem] bg-emerald-950 p-8 text-white"><p className="text-xs font-black uppercase tracking-[.3em] text-emerald-300">Self-service operations</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Run SUR without guessing.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/70">This page explains the normal daily sequence, safety stops and recovery path. Guardian protects data changes; PMS confirms system health.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/admin/guardian" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-emerald-950">Open Guardian</Link><Link href="/health" className="rounded-2xl border border-white/20 px-5 py-3 text-sm font-black">System health</Link></div></header>
<section className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="Daily operating sequence">{daily.map(([t,d,h],i)=><Link href={h} key={t} className="block rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4 hover:border-emerald-400"><p className="text-xs font-black uppercase text-emerald-700">Step {i+1}</p><h2 className="mt-1 text-lg font-black">{t}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></Link>)}</Panel><Panel title="Stop and recover safely">{emergency.map(([t,d])=><div key={t} className="rounded-2xl border border-amber-100 bg-amber-50 p-4"><h2 className="font-black text-amber-950">{t}</h2><p className="mt-2 text-sm leading-6 text-amber-900">{d}</p></div>)}</Panel></section>
<section className="mt-5 rounded-[2rem] border border-emerald-100 bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">PMS schedule</h2><div className="mt-5 grid gap-3 md:grid-cols-3"><Check title="Daily" items={["Login and role access","Pending/duplicate payments","Overdue farm tasks","Wallet and withdrawal exceptions","Backup status"]}/><Check title="Weekly" items={["Tree/QR consistency","Rejected evidence chains","Support backlog","Storage and notification health","Contract pending copies"]}/><Check title="Monthly" items={["Access review","Ledger reconciliation","Restore rehearsal","Legal/settings versions","Five-gate release evidence"]}/></div></section>
<p className="mt-5 rounded-2xl bg-slate-900 p-5 text-sm font-bold leading-7 text-white">Normal business operations are designed to run without a developer. Schema changes, security incidents, failed restores and new feature development still require qualified technical review—Guardian must never be used to bypass that safety boundary.</p></div></main>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-3 rounded-[2rem] border border-emerald-100 bg-white p-6 shadow-sm"><h2 className="mb-4 text-2xl font-black">{title}</h2>{children}</section>}
function Check({title,items}:{title:string;items:string[]}){return <div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black text-emerald-800">{title}</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{items.map(x=><li key={x}>✓ {x}</li>)}</ul></div>}
