"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase/client";

type Row=Record<string,unknown>;
const upper=(value:unknown)=>String(value||"").toUpperCase();

export default function AdminTasksHub(){
 const [assignments,setAssignments]=useState<Row[]>([]),[updates,setUpdates]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function load(){setLoading(true);setMessage("");const [taskResult,updateResult]=await Promise.all([supabase.from("sur_tree_assignments").select("id,status,task_title,assigned_at,updated_at").limit(3000),supabase.from("sur_tree_updates").select("id,status,photo_path").limit(3000)]);setAssignments((taskResult.data||[]) as Row[]);setUpdates((updateResult.data||[]) as Row[]);if(taskResult.error||updateResult.error)setMessage("Some task records could not load. Refresh before making a decision.");setLoading(false)}
 const openTasks=assignments.filter(row=>!["COMPLETED","APPROVED","CANCELLED"].includes(upper(row.status))).length;
 const reviews=updates.filter(row=>["PENDING","PENDING_REVIEW","SUBMITTED"].includes(upper(row.status))).length;
 const resubmissions=updates.filter(row=>["REJECTED","NEEDS_RESUBMISSION","RETURNED"].includes(upper(row.status))).length;
 const recommended=reviews?{title:"Review caretaker evidence",detail:`${reviews} report${reviews===1?" is":"s are"} waiting for approval.`,href:"/admin/care-operations",action:"Review reports"}:resubmissions?{title:"Check requested resubmissions",detail:`${resubmissions} report${resubmissions===1?" needs":"s need"} a corrected submission.`,href:"/admin/care-operations",action:"Open resubmissions"}:openTasks?{title:"Check caretaker schedules",detail:`${openTasks} task${openTasks===1?" is":"s are"} still open.`,href:"/admin/care-operations",action:"Open schedules"}:{title:"Caretaker work is up to date",detail:"No report or schedule currently needs an Admin decision.",href:"/admin/care-operations",action:"View all tasks"};
 return <main className="min-h-screen px-4 py-5 text-[#10271f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1200px]"><header className="rounded-[2rem] bg-[#073d2e] p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#bfe6d5]">Tasks</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Caretaker work and reports</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70">See schedules, submitted photos, approvals, and requests for correction.</p></header>{message&&<p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</p>}<section className="mt-5 rounded-[2rem] border border-[#d9d4c5] bg-[#fff9e8] p-5 shadow-sm sm:p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8a6820]">Recommended action</p><h2 className="mt-2 text-2xl font-black">{loading?"Checking caretaker work…":recommended.title}</h2><p className="mt-2 text-sm leading-6 text-[#68501b]">{loading?"Please wait while the app checks what needs attention.":recommended.detail}</p>{!loading&&<Link href={recommended.href} className="mt-5 inline-flex rounded-2xl bg-[#073d2e] px-5 py-3 text-sm font-black text-white">{recommended.action}</Link>}</section><section className="mt-5 grid gap-4 md:grid-cols-3"><Status title="Open schedules" value={openTasks} detail="Caretaker tasks still in progress"/><Status title="Reports to approve" value={reviews} detail="Photos and notes waiting for Admin"/><Status title="Needs resubmission" value={resubmissions} detail="Reports returned for correction"/></section><Link href="/admin/care-operations" className="mt-5 flex items-center justify-between rounded-[1.75rem] border border-[#d9d4c5] bg-white p-6 font-black shadow-sm"><span>Open all caretaker tasks and reports</span><span className="text-xl">›</span></Link></div></main>;
}

function Status({title,value,detail}:{title:string;value:number;detail:string}){return <div className="rounded-[1.75rem] border border-[#d9d4c5] bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.12em] text-[#687970]">{title}</p><p className="mt-3 text-4xl font-black text-[#073d2e]">{value}</p><p className="mt-2 text-sm leading-6 text-[#718078]">{detail}</p></div>}
