"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase/client";

type Row=Record<string,unknown>;
const upper=(value:unknown)=>String(value||"").toUpperCase();

export default function AdminTreeHub(){
 const [orders,setOrders]=useState<Row[]>([]),[contracts,setContracts]=useState<Row[]>([]),[trees,setTrees]=useState<Row[]>([]),[withdrawals,setWithdrawals]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function load(){setLoading(true);setMessage("");const results=await Promise.all([supabase.from("sur_tree_orders").select("id,status").limit(2000),supabase.from("sur_contracts").select("id,status").limit(2000),supabase.from("sur_trees").select("id,status,caretaker_profile_id,planted_at").limit(3000),supabase.from("withdrawal_requests").select("id,status").limit(2000)]);setOrders((results[0].data||[]) as Row[]);setContracts((results[1].data||[]) as Row[]);setTrees((results[2].data||[]) as Row[]);setWithdrawals((results[3].data||[]) as Row[]);if(results.some(result=>result.error))setMessage("Some tree journey records could not load. Refresh before making a decision.");setLoading(false)}
 const payments=orders.filter(row=>["PENDING","PENDING_VERIFICATION","MANUAL_REVIEW"].includes(upper(row.status))).length;
 const signatures=contracts.filter(row=>["DRAFT","PENDING","CUSTOMER_SIGNATURE_PENDING","AWAITING_CUSTOMER_SIGNATURE"].includes(upper(row.status))).length;
 const setup=trees.filter(row=>!row.caretaker_profile_id||!row.planted_at).length;
 const payouts=withdrawals.filter(row=>["PENDING","PENDING_REVIEW","PENDING_VERIFICATION"].includes(upper(row.status))).length;
 const recommended=payments?{title:"Verify a tree payment",detail:`${payments} payment${payments===1?" is":"s are"} waiting for review.`,href:"/admin/orders",action:"Review payments"}:signatures?{title:"Complete a tree contract",detail:`${signatures} contract${signatures===1?" needs":"s need"} attention.`,href:"/admin/legal",action:"Review contracts"}:setup?{title:"Complete tree setup",detail:`${setup} tree${setup===1?" needs":"s need"} assignment or planting details.`,href:"/admin/tree-registry",action:"Open tree setup"}:payouts?{title:"Process a payout request",detail:`${payouts} payout request${payouts===1?" is":"s are"} waiting.`,href:"/admin/withdrawals",action:"Review payouts"}:{title:"Tree journey is clear",detail:"No payment, contract, setup, or payout is currently waiting.",href:"/admin/tree-registry",action:"View all trees"};
 const stages=[{label:"Order & payment",count:payments,href:"/admin/orders",detail:"Verify exact payment and receipt"},{label:"Contract",count:signatures,href:"/admin/legal",detail:"Review signing and legal records"},{label:"Assignment & planting",count:setup,href:"/admin/tree-registry",detail:"Complete Tree ID, caretaker, and planting"},{label:"Care",count:0,href:"/admin/care-operations",detail:"Open caretaker work and updates"},{label:"Sale & payout",count:payouts,href:"/admin/withdrawals",detail:"Review balance and payout requests"}];
 return <main className="min-h-screen px-4 py-5 text-[#10271f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1200px]"><header className="rounded-[2rem] bg-[#073d2e] p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#bfe6d5]">Tree</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">One clear tree journey</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70">Follow each purchase from payment to planting, care, sale, and payout.</p></header>{message&&<p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</p>}<section className="mt-5 rounded-[2rem] border border-[#d9d4c5] bg-[#fff9e8] p-5 shadow-sm sm:p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8a6820]">Recommended action</p><h2 className="mt-2 text-2xl font-black">{loading?"Checking the tree journey…":recommended.title}</h2><p className="mt-2 text-sm leading-6 text-[#68501b]">{loading?"Please wait while the app checks what needs attention.":recommended.detail}</p>{!loading&&<Link href={recommended.href} className="mt-5 inline-flex rounded-2xl bg-[#073d2e] px-5 py-3 text-sm font-black text-white">{recommended.action}</Link>}</section><section className="mt-5 grid gap-3">{stages.map((stage,index)=><Link key={stage.label} href={stage.href} className="flex items-center gap-4 rounded-2xl border border-[#d9d4c5] bg-white p-5 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e7f3ec] font-black text-[#073d2e]">{index+1}</span><span className="min-w-0 flex-1"><b className="block text-lg">{stage.label}</b><small className="mt-1 block text-sm text-[#687970]">{stage.detail}</small></span>{stage.count>0&&<span className="grid h-10 min-w-10 place-items-center rounded-full bg-[#dda93e] px-3 text-sm font-black text-[#211906]">{stage.count}</span>}<b className="text-xl">›</b></Link>)}</section></div></main>;
}
