"use client";
import type { ReactNode } from "react";
export type Row = Record<string, unknown>;
export const upper = (value: unknown) => String(value || "").toUpperCase();
export const pretty = (value: unknown) => String(value || "PENDING").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
export const dateText = (value: unknown) => { const date = new Date(String(value || "")); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" }); };
export function AdminPage({ eyebrow, title, detail, children, action }: { eyebrow: string; title: string; detail: string; children: ReactNode; action?: ReactNode }) { return <main className="min-h-screen bg-[#f4f1e7] px-3 py-4 text-[#10271f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1320px]"><header className="flex flex-col gap-4 rounded-[1.75rem] bg-[#073d2e] p-5 text-white shadow-xl shadow-[#073d2e]/10 sm:p-7 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-[#9ee7c5]">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">{detail}</p></div>{action}</header>{children}</div></main>; }
export function Recommended({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <section className="mt-5 rounded-[1.75rem] border border-[#e7d7a9] bg-[#fff9e8] p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#8a6820]">Recommended action</p><h2 className="mt-2 text-2xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-[#68501b]">{detail}</p>{action && <div className="mt-4">{action}</div>}</section>; }
export function StatusPill({ value }: { value: unknown }) { const status = upper(value); const tone = status.includes("APPROV") || status.includes("ACTIVE") || status.includes("COMPLETE") || status.includes("SIGNED") ? "bg-emerald-100 text-emerald-800" : status.includes("REJECT") || status.includes("RETURN") ? "bg-red-100 text-red-800" : status.includes("WAIT") || status.includes("PENDING") || status.includes("REVIEW") ? "bg-amber-100 text-amber-900" : "bg-sky-100 text-sky-800"; return <span className={`shrink-0 rounded-full px-3 py-1.5 text-[10px] font-black ${tone}`}>{pretty(status)}</span>; }
export function FilterBar({ values, selected, onChange }: { values: string[]; selected: string; onChange: (value: string) => void }) { return <div className="flex gap-2 overflow-auto pb-1">{values.map((value) => <button key={value} type="button" onClick={() => onChange(value)} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-black ${selected === value ? "border-[#073d2e] bg-[#073d2e] text-white" : "border-[#d9d4c5] bg-white text-[#65756e]"}`}>{pretty(value)}</button>)}</div>; }
export function SearchBox({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="min-h-11 w-full rounded-2xl border border-[#d9d4c5] bg-white px-4 text-sm font-bold outline-none focus:border-[#08745b] sm:max-w-sm" />; }
export function Drawer({ open, title, eyebrow, onClose, children }: { open: boolean; title: string; eyebrow: string; onClose: () => void; children: ReactNode }) { if (!open) return null; return <div className="fixed inset-0 z-50 bg-[#061b14]/60" onMouseDown={onClose}><aside role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()} className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-[#f4f1e7] p-4 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#08745b]">{eyebrow}</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{title}</h2></div><button onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-white text-xl shadow-sm">×</button></div><div className="mt-5 space-y-4">{children}</div></aside></div>; }
export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-[1.6rem] border border-[#d9d4c5] bg-white p-5 shadow-sm ${className}`}>{children}</section>; }
export function Info({ label, value }: { label: string; value: ReactNode }) { return <div className="flex items-start justify-between gap-5 border-b border-[#eee9dd] py-3 text-sm last:border-0"><span className="text-[#718078]">{label}</span><b className="max-w-[65%] break-words text-right">{value || "—"}</b></div>; }
export const primaryButton = "rounded-2xl bg-[#073d2e] px-5 py-3 text-sm font-black text-white disabled:opacity-40";
export const dangerButton = "rounded-2xl border border-red-200 bg-white px-5 py-3 text-sm font-black text-red-700 disabled:opacity-40";
