"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/app/lib/supabase/client";

type Row=Record<string,unknown>;
const upper=(value:unknown)=>String(value||"").toUpperCase();

export default function AdminAccountsHub(){
 const [customers,setCustomers]=useState<Row[]>([]),[caretakers,setCaretakers]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 async function load(){setLoading(true);setMessage("");const [profiles,gardeners]=await Promise.all([supabase.from("profiles").select("id,role,account_status,kyc_status").in("role",["COPLANTER","INVESTOR","CUSTOMER"]).limit(2000),supabase.from("gardeners").select("id,status").limit(2000)]);setCustomers((profiles.data||[]) as Row[]);setCaretakers((gardeners.data||[]) as Row[]);if(profiles.error||gardeners.error)setMessage("Some account records could not load. Refresh before making a decision.");setLoading(false)}
 const pendingCustomers=customers.filter(row=>["PENDING","UNDER_REVIEW","SUBMITTED"].includes(upper(row.kyc_status))).length;
 const pendingCaretakers=caretakers.filter(row=>["PENDING","UNDER_REVIEW","SUBMITTED"].includes(upper(row.status))).length;
 const recommended=pendingCustomers?{title:"Review customer identity",detail:`${pendingCustomers} customer${pendingCustomers===1?" is":"s are"} waiting for identity review.`,href:"/admin/coplanters",action:"Review customers"}:pendingCaretakers?{title:"Review caretaker application",detail:`${pendingCaretakers} caretaker application${pendingCaretakers===1?" is":"s are"} waiting.`,href:"/admin/gardener",action:"Review caretakers"}:{title:"No account review waiting",detail:"Customer and caretaker queues are clear.",href:"/admin/coplanters",action:"View all accounts"};
 return <main className="min-h-screen px-4 py-5 text-[#10271f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1200px]"><header className="rounded-[2rem] bg-[#073d2e] p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#bfe6d5]">Accounts</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">People and account approval</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70">Review customers and caretakers without opening technical records.</p></header>{message&&<p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</p>}<section className="mt-5 rounded-[2rem] border border-[#d9d4c5] bg-[#fff9e8] p-5 shadow-sm sm:p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8a6820]">Recommended action</p><h2 className="mt-2 text-2xl font-black">{loading?"Checking account queues…":recommended.title}</h2><p className="mt-2 text-sm leading-6 text-[#68501b]">{loading?"Please wait while the app checks who needs attention.":recommended.detail}</p>{!loading&&<Link href={recommended.href} className="mt-5 inline-flex rounded-2xl bg-[#073d2e] px-5 py-3 text-sm font-black text-white">{recommended.action}</Link>}</section><section className="mt-5 grid gap-4 md:grid-cols-2"><Queue title="Customers" count={pendingCustomers} total={customers.length} detail="Identity, status, and customer account review" href="/admin/coplanters"/><Queue title="Caretakers" count={pendingCaretakers} total={caretakers.length} detail="Application, verification, and caretaker access" href="/admin/gardener"/></section></div></main>;
}

function Queue({title,count,total,detail,href}:{title:string;count:number;total:number;detail:string;href:string}){return <Link href={href} className="rounded-[1.75rem] border border-[#d9d4c5] bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-[#687970]">{detail}</p></div><span className={`grid h-12 min-w-12 place-items-center rounded-full px-3 font-black ${count?"bg-[#dda93e] text-[#211906]":"bg-[#dfe9e4] text-[#53665d]"}`}>{count}</span></div><p className="mt-5 text-sm font-bold text-[#167553]">{total} total · Open list →</p></Link>}
