"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getAuthenticatedProfile } from "@/app/lib/auth/session";
import { supabase } from "@/app/lib/supabase/client";

type Tree={id:string;tree_id:string;nickname:string|null;care_plan:string;created_at:string};
type Update={id:string;tree_id:string;observed_on:string;health_status:string|null;notes:string|null;photo_path:string|null;photo_url?:string;created_at:string};

export default function CareJournalPage(){
 const [trees,setTrees]=useState<Tree[]>([]),[updates,setUpdates]=useState<Update[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError("");const profile=await getAuthenticatedProfile();if(!profile){setError("Please sign in again.");setLoading(false);return}const treeResult=await supabase.from("sur_trees").select("id,tree_id,nickname,care_plan,created_at").eq("profile_id",profile.id).order("created_at",{ascending:false});if(treeResult.error){setError("Care Journal is temporarily unavailable.");setLoading(false);return}const ownTrees=(treeResult.data||[]) as Tree[];setTrees(ownTrees);setSelected(current=>current||ownTrees[0]?.id||"");if(!ownTrees.length){setLoading(false);return}const updateResult=await supabase.from("sur_tree_updates").select("id,tree_id,observed_on,health_status,notes,photo_path,created_at").in("tree_id",ownTrees.map(tree=>tree.id)).eq("status","APPROVED").order("observed_on",{ascending:false});if(updateResult.error){setError("Updates could not load. Please retry.");setUpdates([]);setLoading(false);return}const signed=await Promise.all(((updateResult.data||[]) as Update[]).map(async update=>{if(!update.photo_path)return update;const {data}=await supabase.storage.from("sur-tree-evidence").createSignedUrl(update.photo_path,600);return {...update,photo_url:data?.signedUrl||""}}));setUpdates(signed);setLoading(false)}
 const tree=trees.find(item=>item.id===selected)||null,feed=useMemo(()=>updates.filter(update=>update.tree_id===selected),[updates,selected]);
 return <main className="min-h-screen bg-[#f3f0e6] pb-12 text-[#12231c]"><header className="sticky top-0 z-30 border-b border-[#dbe5df] bg-[#f7f3e8]/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-3xl items-center justify-between px-4"><Link href="/investor/my-trees" className="text-sm font-black text-[#0b3d2e]">← My Trees</Link><b className="text-sm tracking-[.08em]">CARE JOURNAL</b><button onClick={()=>void load()} className="rounded-full border border-[#dbe5df] bg-white px-4 py-2 text-xs font-black">Refresh</button></div></header><section className="mx-auto max-w-3xl px-4 py-6">
  <div className="rounded-[1.75rem] bg-[#073c2d] p-5 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.16em] text-[#b9d9ca]">Tree care</p><h1 className="mt-2 font-serif text-3xl font-black">Care Journal</h1><p className="mt-2 text-sm leading-6 text-white/70">Approved plantation photos and care records for your tree.</p>{trees.length>1&&<select value={selected} onChange={event=>setSelected(event.target.value)} className="mt-5 w-full rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-black text-white">{trees.map((item,index)=><option key={item.id} value={item.id} className="text-black">{item.nickname||`My Agarwood Tree ${index+1}`}</option>)}</select>}</div>
  {error&&<p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}{loading?<p className="mt-6 text-center text-sm font-bold text-[#64756d]">Loading Care Journal…</p>:!tree?<Empty text="Your Care Journal will appear after your first tree is approved."/>:<><Coverage tree={tree}/><div className="mt-7 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#167553]">Latest first</p><h2 className="mt-1 text-2xl font-black">Plantation Updates</h2></div><span className="rounded-full bg-white px-3 py-2 text-xs font-black text-[#64756d]">{feed.length} posts</span></div><div className="mt-4 grid gap-5">{feed.length?feed.map(update=><Post key={update.id} update={update} tree={tree}/>):<Empty text="No approved plantation update yet. New caretaker submissions will appear here after Admin review."/>}</div></>}
 </section></main>
}

function Coverage({tree}:{tree:Tree}){const plan=tree.care_plan.toUpperCase();if(plan==="ONE_TIME")return <section className="mt-5 rounded-2xl border border-[#bfe3d0] bg-[#e7f5ed] p-5"><p className="text-xs font-black uppercase tracking-[.12em] text-[#167553]">One-Time Care</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><b className="text-xl">Care fully paid</b><p className="mt-1 text-sm text-[#587069]">No monthly payment required.</p></div><span className="rounded-full bg-white px-4 py-2 text-xs font-black text-[#167553]">FULL COVERAGE</span></div></section>;if(plan==="MONTHLY")return <section className="mt-5 rounded-2xl border border-[#e5d4a4] bg-[#fff8dc] p-5"><p className="text-xs font-black uppercase tracking-[.12em] text-[#8b6519]">Monthly Care</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><b className="text-xl">₱200 per month</b><p className="mt-1 text-sm text-[#735f35]">Keep your care coverage and new journal updates current.</p></div><Link href="/investor/wallet" className="rounded-xl bg-[#d5a344] px-5 py-3 text-sm font-black text-[#2e2108]">Pay Monthly Care</Link></div></section>;return <section className="mt-5 rounded-2xl border border-[#dbe5df] bg-white p-5"><p className="text-xs font-black uppercase tracking-[.12em] text-[#64756d]">Basic Care</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><b className="text-xl">Planting update only</b><p className="mt-1 text-sm text-[#64756d]">Regular Care Journal updates are not included.</p></div><Link href="/investor/support" className="rounded-xl bg-[#0b3d2e] px-5 py-3 text-sm font-black text-white">Choose Care Plan</Link></div></section>}
function Post({update,tree}:{update:Update;tree:Tree}){const title=taskTitle(update),photo=update.photo_url||"";return <article className="overflow-hidden rounded-[1.75rem] border border-[#dbe5df] bg-white shadow-[0_15px_40px_rgba(15,48,36,.08)]"><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-xs font-bold text-[#718078]">{date(update.observed_on||update.created_at)} · {tree.nickname||"My Agarwood Tree"}</p></div><span className="rounded-full bg-[#e7f5ed] px-3 py-2 text-[10px] font-black uppercase text-[#167553]">{friendlyHealth(update.health_status)}</span></div></div>{photo&&<div className="relative aspect-[4/3] w-full bg-[#dcebdc] sm:aspect-video"><Image src={photo} alt={title} fill unoptimized className="object-cover"/></div>}<div className="p-5"><p className="text-sm leading-7 text-[#52655d]">{update.notes||"Plantation care task completed and approved by Admin."}</p><p className="mt-4 border-t border-[#edf0ed] pt-4 text-xs font-black text-[#8a9891]">Approved care record</p></div></article>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-[1.5rem] border border-dashed border-[#cbd8d1] bg-white p-8 text-center text-sm font-bold leading-6 text-[#64756d]">{text}</div>}
function taskTitle(update:Update){const note=String(update.notes||"").trim();if(note){const first=note.split(/[.!?\n]/)[0].trim();if(first.length>=4&&first.length<=60)return first}return "Plantation Care Update"}
function friendlyHealth(value?:string|null){return ({HEALTHY:"Healthy",NEEDS_ATTENTION:"Needs attention",TREATMENT:"Under treatment",DAMAGED:"Damaged",REPLACEMENT_REVIEW:"Replacement review"} as Record<string,string>)[String(value||"").toUpperCase()]||"Awaiting update"}
function date(value:string){return new Intl.DateTimeFormat("en-PH",{day:"numeric",month:"long",year:"numeric"}).format(new Date(value))}
